export const InsightCategory = {
  MARGINALISED_AUTHOR: "MARGINALISED_AUTHOR",
  WORKING_ALONE_AND_TOGETHER: "WORKING_ALONE_AND_TOGETHER",
  BETWEEN_UNIQUENESS_AND_FORMULA: "BETWEEN_UNIQUENESS_AND_FORMULA",
  FREELANCE: "FREELANCE"
}

export const insightCategoryConfigs = {
  [InsightCategory.MARGINALISED_AUTHOR]: {
    title: "Marginalised Author",
    description: `The position of the screenwriter in the film industry has historically been marginalised, meaning that they’re often overlooked — and yes, that can seriously hurt their ego. This marginalisation shows up in many ways: ambiguous status of screenwriter, loss of creative control during development, little recognition for the writer’s artistic input, and the fact that the title of "main creator" usually goes to the director. In Hollywood, it’s even worse, thanks to the rewriting system and a complicated credit structure that doesn’t always reflect who actually did the work. \n\nSee the insights you unlocked to know more !`,
  },
  [InsightCategory.WORKING_ALONE_AND_TOGETHER]: {
    title: "Working Alone and Together",
    description: `Screenplay development is built on a constant tension between individual and collaborative modes of work. While the writing itself is often done alone, a screenplay only truly takes shape through collaboration — with the producer, the director, the actors, and others. Navigating this process requires the screenwriter to integrate feedback while defending their own vision. And yes, getting notes on something you wrote from the heart can hurt — but staying professional is key. In the end, relationships are a screenwriter’s most important asset. \n\nWant to dig deeper? See the insights you've unlocked.`,
  },
  [InsightCategory.BETWEEN_UNIQUENESS_AND_FORMULA]: {
    title: "Between Uniqueness and Formula",
    description: `Screenwriters face a double imperative: to create work that is original enough to stand out, while still conforming to well-established norms. That actually is true for many other forms of art, but the tension is particularly strong in Hollywood, where financial stakes push studios to rely on proven formulas. The dominant industry mindset, reinforced by screenwriting manuals and courses, shapes expectations around what makes a “good” script, thus limiting the writer’s artistic freedom. In other words, be creative — but not too creative.\n\nSee the insights you unlocked to know more !`
  },
  [InsightCategory.FREELANCE]: {
    title: "Freelance",
    description: `The screenwriting profession in Hollywood today operates within a freelance framework.  Sounds flexible. Sounds free. But in reality? It means instability, precarity, and a very competitive market. Only a small elite gains access to the best opportunities, while ordinary screenwriters must juggle side jobs (related or completely unrelated to screenwriting) just to make ends meet, all while constantly investing in their reputation. \n\nCurious to know more? Your unlocked insights are waiting.`
  },
};

export const insightList =  {
  "artistcraftsman": {
		category: "MARGINALISED_AUTHOR",
    title: "Screenwriter: Artist or Craftsman?",
    body: "Back in the early days of cinema, screenplays were barely a thing. Most films were improvised on the spot, with directors, actors, and crew just winging it. What passed for a “script” was usually a few scribbled notes — more like reminders than actual plans. The result? Chaos. Props vanished and reappeared mid-scene, costumes changed for no reason, and characters magically teleported around the screen.\n\nThen came Thomas Harper Ince (1820-1994), who decided enough was enough. He brought order to the madness, introducing structured scripts that broke scenes down shot by shot. The screenplay became the central document for production — full of technical details like lighting, costumes, camera angles, props, and sound cues.\n\nBut here’s the twist: the more technical the script became, the harder it was to see it as a work of art. And that’s the heart of the screenwriter’s identity crisis — are they an artist shaping stories, or just a cog in the production machine?"
  },
  "auteurtheory": {
		category: "MARGINALISED_AUTHOR",
    title: "Auteur Theory: Director as Main Artist ",
    body: "One major reason screenwriters got pushed to the sidelines was the rise of auteur theory — a critical movement in film that emerged in 1950s France, championed by director François Truffaut and film critic André Bazin. Auteur theory established a lasting dominance of the director as the primary creator of the film.\n\nThis vision took off worldwide, reshaping how people studied, critiqued, and taught cinema. Suddenly, the screenplay was seen as nothing more than a blueprint — something to build from, not something of artistic value in itself.\n\nSure, auteur theory helped cinema gain recognition as a serious and independent art form, but it came at the cost of diminishing the collaborative nature of filmmaking and the role of the screenwriter. Bazin famously said: “The director writes in film”. Then… What exactly does the screenwriter do?"
  },
  "creativecontrol": {
		category: "MARGINALISED_AUTHOR",
    title: "Loss of Creative Control ",
    body: "In Hollywood, the screenwriter's lack of creative control goes even further thanks to the rewriting — a practice where new writers are brought onto a project to deliver another draft of the script. In other words: if you're working on a Hollywood film, there's a 99.9% chance you'll be fired. And bizarrely, sometimes that’s even considered a good sign — it means the project is moving forward and more likely to get greenlit."
  },
  "creditsystem": {
		category: "MARGINALISED_AUTHOR",
    title: "Hollywood System of Credits",
    body: "The practice of rewrites, where several writers work on the same project in succession, is tough enough for screenwriters. But what really stings is that Hollywood’s credit system doesn’t always reflect their actual contribution. For example, it can happen that out of four writers working on a project, the most important contributions are made by the second and fourth writers, but according to the system, it’s the first and third who receive the credit. So yes. You may write the heart of the story… and never see your name on screen.\n\n"
  },
  "scriptdevelopment": {
		category: "WORKING_ALONE_AND_TOGETHER",
    title: "Script Development",
    body: "Screenwriting is often imagined as a lonely craft — a solitary writer, hunched over a laptop, weaving stories in silence. And at first, it kind of is: the earliest drafts are usually written in isolation, before anyone else joins the project.\n\nBut that’s where the solo act ends. From the moment a screenplay has a real shot at being made, the writer’s work enters a new phase: collaboration. Producers, directors, executives, actors, friends, friends of friends… suddenly, everyone has notes. Welcome to the Screen Idea Work Group — a flexible, ever-shifting team where everyone gets a say in how the story evolves.\n\nSometimes that collaboration is rich and productive. Other times, it’s chaos and misunderstanding.  Through it all, the writer is expected to adapt, negotiate, decode, defend their vision — and, of course, stay charming about it.\n\nYou'll learn strategies to survive through development in the Development Survival Guide. "
  },
  "survivalguide1": {
		category: "WORKING_ALONE_AND_TOGETHER",
    title: "Script Development Survival Guide. Part I ",
    body: "To survive the development process, screenwriters need more than talent. They need to be a psychologist, a negotiator, and a diplomat — all at once. Here is the first part of the Development Survival Guide: \n\n1. Сhoose Your Allies right: Before you dive into development, know who you’re working with. If you can, choose a producer or director who shares your vision. Shared creative and cultural references help build trust, while mismatched visions can sink the project.\n\n2. If the idea is yours, figure out its essence from the start.  It'll be your compass through the chaos of development — helping you stay open to good suggestions, but also knowing when to push back if changes start watering down the story or drowning out your voice.\n\n3. If the idea comes from a producer or a director, get a clear brief. Ask questions to understand what exactly they love about it. Otherwise, you might end up cutting something crucial without even realizing it.\n\n4. And one more thing: when you get feedback from a producer or especially a director, don't just take it at face value. You need to read between the lines. Sometimes, a note isn’t really about the script at all. It's about fear, doubt, or a cry for help from someone who's unsure. Maybe you don't need to rewrite the whole script — maybe you just need to give them a little reassurance.\n\nFind more tips in Part II of the guide!"
  },
  "survivalguide2": {
		category: "WORKING_ALONE_AND_TOGETHER",
    title: "Script Development Survival Guide. Part II",
    body: "Here are some more tips to navigate the development process : \n\n1. In the film industry, reputation is everything. Every project you work on could open (or close) doors for your future. That’s why it’s crucial to stay professional, positive, and easy to work with — no matter how frustrating things get. You can’t control every note or every twist in the development process. But you can control how you handle people. And sometimes, that matters even more than your talent as a writer.\n\n2. Avoid getting too defensive and always stay open to new ideas. When you get feedback, take a breath. You don’t have to respond right away. Listen first — react later.\n\n3.Stay calm and respectful, even when it feels like the note makes no sense. Sometimes, a bad comment isn’t the real danger. Burning bridges is.\n\n4. Always take notes during meetings. Meetings blur together. Notes will help you keep track of the feedback.\n\n5. Know when to walk away. If notes keep twisting the essence of your story beyond saving, it might be time to step back.\n\n6. And finally, if you’re pushed out, don’t take it personally. It’s not about you. It’s about the project. And if you’re lucky, you’ll get another chance to prove yourself somewhere else."
  },
  "developmenthell": {
		category: "WORKING_ALONE_AND_TOGETHER",
    title: "Development Hell",
    body: "In Hollywood, maintaining the delicate balance between your own creative voice and collaboration is particularly hard. Projects get stuck in development hell — endless rewrites, shifting priorities, new executives, changing studio strategies, and stacks of contradictory notes. Here's roughly how it goes:\n\n1. The screenwriter turns in what they believe is a perfect draft.\n\n2. The producer (or studio executive) doesn’t read it themselves — they send it to a professional script reader. At this point, the writer might already be fired and replaced. If not, they receive notes.\n\n3. Then the producer might actually read it and add their own feedback — to justify their credit / high salary / job title / parking spot. After that, they might hire a new writer for a rewrite — or, with a bit of luck, stick with the original one.\n\n4. The screenwriter does their best to implement everyone’s conflicting suggestions, then submits a new draft.\n\n5. That version goes to the director and actors — who will, of course, want their own rewrites. And since everyone’s ideas contradict each other, they all blame the screenwriter.\n\n6. And so... the writer is replaced, and the whole cycle starts over.\n\nAnd the saddest part? The story doesn’t always improve through development. It can easily be rewritten to death — stripped of its original voice and spark. Or maybe the real saddest part is this: Most screenplays never make it out of development. They get stuck there for good — often for reasons completely outside the writer’s control. Like when a new studio executive comes in and decides to cancel the project. Just like that."
  },
  "doublestandards": {
		category: "BETWEEN_UNIQUENESS_AND_FORMULA",
    title: "Double Standards",
    body: "Sociologist Pierre Bourdieu described the world of art as a battlefield between two principles. The hétéronome principle values economic success — making money, pleasing studios, reaching wide audiences. The autonome principle values artistic recognition — originality, critical acclaim, and lasting cultural impact.\n\nThese two principles don’t cancel each other out but rather work alongside one another. A script, like any work of art, is judged on both scales: it has to be original enough to stand out, but standard and proven enough to sell.\n\nDepending on the time and the market, the balance shifts. In indie cinema, originality can outweigh commercial success. In Hollywood, big budgets mean big pressure — and economic success almost always wins. To limit financial risks, studios stick to proven formulas, franchises, remakes, and projects with predictable mass appeal.\n\nThey ask for \"something original\", but also \"something just like the last big hit\". This tension forms the heart of what Bourdieu called “doxa” — the unwritten belief system about what a “good script” should be. Actually, it’s not that unwritten: the Hollywood doxa is spread and reinforced by screenwriting courses and manuals.\n\nUnlock other insights to learn more about the Hollywood doxa!"
  },
  "screenwritingmanuals": {
		category: "BETWEEN_UNIQUENESS_AND_FORMULA",
    title: "Screenwriting Manuals and the Hollywood Doxa ",
    body: `Most texts ever written about screenwriting are, in fact, screenwriting manuals. The recent boom in screenwriting literature began with \"Screenplay\" by Syd Field in 1979, and new titles have kept coming ever since.
    \nSo what exactly do these books teach? And how do they reinforce the Hollywood doxa? Let’s take a closer look. Many manuals sound like they promise a magic formula for success and claim to be the only place you’ll find it. You’ll see names like \"The Screenwriting Bible\" (David Trottier), \"Writing Movies for Fun and Profit: How We Made a Billion Dollars at the Box Office and You Can, Too!\" (Thomas Lennon & Robert Ben Garant), or \"Save the Cat! The Last Book on Screenwriting You’ll Ever Need\" (Blake Snyder).
    \nBut the truth is most of these books say the same thing, just using slightly different terms to make it sound fresh. They all push a fairly narrow view of storytelling, the one based on the structure: the classic Aristotelian three-act model, a clear central conflict, and an active protagonist with a defined goal.\n\nAlongside storytelling advice, they push a commercial mindset. You’re not just a writer — you’re a businessman. You need to pitch, sell, network, build your brand, and fit into the market… All while staying creative and original. That’s the contradiction at the heart of the Hollywood doxa:  Trust your voice… but only if it fits the system.`
  },
  "ruleskill": {
		category: "BETWEEN_UNIQUENESS_AND_FORMULA",
    title: "Rules That Kill Creativity?",
    body: "Many writers and researchers argue that screenwriting manuals might not be so great for creativity, and some turn to alternative approaches instead. Let’s take a look at the main critiques they raise.\n\nManuals present storytelling as a step-by-step formula and focus heavily on technical details like formatting and page counts. This creates the illusion that anyone can master screenwriting just by following their method. But real creativity is more complex than that.\n\nSome writers say manuals can be useful if used selectively. But follow the rules blindly, and you risk ending up with scripts that “look right” but don’t move anyone. As French screenwriter Jean-Claude Carrière put it: “The rules taught by American instructors only produce déjà vu.”\n\nOthers go further, arguing that the formulaic approach of these manuals isn’t just unhelpful — it can actually harm creativity as it shuts down risk, ambiguity, and uncertainty, all of which are psychologically essential to the creative process.\n\nThe constant emphasis on commercial success, promoted by these manuals, doesn’t help either. Creativity thrives on intrinsic motivation — the joy and inspiration that come from the work itself. When that’s replaced by financial pressure, both creativity and engagement suffer.\n\nAnd yet, these manuals still dominate. Why? Because the industry fears risk. Studios want predictable outcomes — not bold experiments. They like that manuals offer a clear checklist of what a “good” script should have. And if you don’t follow it, you might be labeled “too experimental,” “not marketable,” or just “difficult\".\n\nSo yes — write something brilliant.  Just make sure it ticks all the boxes."
  },
  "goldenageend": {
		category: "FREELANCE",
    title: "The End of the Golden Age",
    body: "The studio era in Hollywood (1920s to around 1950) is often called the Golden Age of Hollywood. For creative personnel, it truly was golden in some ways: they were employed internally by major studios, which guaranteed them stable, secure jobs for relatively long periods.\n\nBut starting in the 1950s, Hollywood began shifting from the old studio system to a freelance model. This new structure made studios more flexible and adaptive — they could hire and fire screenwriters project by project. For writers, though, it meant a much more precarious and insecure career. Stability was replaced by a constant need to hustle for the next job.\n\nUncover other insights to learn the rules of the screenwriting freelance market. But spoiler: they’re tough."
  },
  "dayjobs": {
		category: "FREELANCE",
    title: "Day Jobs",
    body: "Because freelance work is so unstable, even experienced screenwriters often can’t live on writing alone. To make ends meet, they find other sources of income, called “day jobs\”. Sometimes these day jobs are related to screenwriting — like teaching screenwriting, editing scripts, or writing for theater, podcasts, or online platforms.\n\nOther times, they have nothing to do with the industry. Writers might work as business assistants, realtors, teachers... or housewives (or husbands).\n\nThe best day jobs, according to insiders, are the ones that pay the bills without draining the mental energy you need to keep writing."
  },
  "agentinsight": {
		category: "FREELANCE",
    title: "Agent",
    body: `To navigate the Hollywood industry and get real opportunities, you need an agent. Agents do more than just negotiate deals — they legitimize you. When an agent represents you, it signals to producers and studios that you're worth their attention.\n\nTechnically, you could send an unsolicited script directly to a studio — but in practice, most studios won’t even read it. An agent becomes your passport into the real industry, giving you access to networks, projects, and chances that would otherwise stay closed.\n\nThe thing is, getting an agent isn’t that simple. You need something to offer first. So most likely, your first project will have to be done on your own, just to get their attention.`,
  },
  "ladder": {
		category: "FREELANCE",
    title: "Climbing the Reputation Ladder",
    body: "In screenwriting, there are no official qualifications that guarantee your skills. That’s why in Hollywood, your career doesn’t run on diplomas — it runs on your reputation and past successes. Producers don’t want to take chances on unknown writers; it’s much safer to stick with people they already know can deliver.\n\nThis creates a brutal cycle: the more credits and wins you have, the easier it gets to land the next job. Over time, the industry splits into two camps: a small elite of writer-producers who command the biggest projects and the best deals, and everyone else, scrambling for survival.\n\nMoving from \"ordinary writer\" to \"elite writer\" is harder than it looks because of the matching process : big-budget producers only want the biggest names — people they can trust to bring success. Smaller projects can’t afford those stars, so they work with cheaper, lesser-known talent. And since success breeds success, the gap between the two sides just keeps growing.\n\nIt doesn’t help that professions in Hollywood are highly flexible: the ranks of elite writers are constantly filled from the top of other professions, as successful actors, directors, and producers cross over into screenwriting. So if you're not already at the top, the ladder isn't just steep — it’s practically vertical."
  },
  "writerenterpreneur": {
		category: "FREELANCE",
    title: "Writer Enterpreneur",
    body: "In Hollywood, being a good writer is only half the battle. You also need to be an entrepreneur. There’s no set career path, no guaranteed formula for success. Even a fancy film school diploma doesn’t promise you a career — it just gives you a few more contacts to start with.\n\nIf you want to survive, you have to build your own path: you need to constantly network, pitch, self-promote and stay visible. And for many writers, that's the hardest part. They just wanted to write, they didn’t sign up to be a one-person sales team. But in today’s industry, you have no choice."
  },
  "salaries": {
		category: "FREELANCE",
    title: "Salaries",
    body: "Now let’s talk money. Maybe you’ve heard about some mind-blowing spec script deals — like when Joe Eszterhas got $3 million for the Basic Instinct screenplay. Sounds great, right? But let me stop you before you start dreaming about yachts: those cases are rare, and even the biggest payouts today aren’t as high.\n\nTo get a more realistic picture, let’s look at the numbers: the Writers Guild minimum for an original screenplay in 2023 ranges from $85,281 to $160,084, depending on the film’s budget. Ok, I agree — that doesn’t sound bad either.\n\nBut here’s the catch: you never know when you’ll get your next gig. You might sell a script once,  and then not sell anything for three or five years. Or ever again. Historical data shows that two-thirds of screenwriters only ever worked on a single film."
  },
  "wga": {
		category: "FREELANCE",
    title: "Writers Guild of America",
    body: "If you’ve done enough work for a company that’s signed a collective agreement with the Guild, you’ll have to join the Writers Guild of America (WGA) — either WGA East (based in New York) or WGA West (based in Los Angeles).\n\nThe WGA isn’t just a union — it’s your legal and professional shield. It protects writers’ rights, negotiates fair contracts, sets minimum salaries, fights for better conditions, advocates for copyright laws, and defends writers’ collective interests.\n\nThe importance of the Guild is hard to overstate. But individually, writers have mixed feelings about it. For some, it’s a lifesaver. For others, it’s a stamp of professional recognition. And for a few, it’s just another obligation.\n\nStrikes help explain this ambivalence. When the Guild calls a strike, you have to stop working, even if it means months without income. The 2023 strike, for example, won major victories like better streaming residuals and protections against AI. But it also left many writers without work for months, deepening financial instability across the entire industry. By 2024, production levels still hadn’t fully recovered, studios became more cautious, and jobs became harder to find.\n\nSo yes — the WGA protects you. But when strikes hit, it’s the writers who pay the price."
  },
  "why": {
		category: "FREELANCE",
    title: "Why People Become Screenwriters",
    body: "Despite unstable project flow, long hours, financial insecurity, and brutal competition, Hollywood keeps attracting new screenwriters from all over the world. And I guess after everything you’ve seen, you might be asking yourself: Why? Why do people want to be screenwriters?\n\nOne reason is economical. Big success stories with big paychecks make it seem possible, even if the chance of succeeding is tiny. And because of that tiny chance, many aspiring screenwriters are willing to accept unstable, low-paid, or even unpaid work at the start of their careers — just to build experience and invest in their reputation. Thus, the modern creative economy thrives on self-exploitation. And that’s the paradox: the more \"free\" people are to chase their creative dreams, the easier it is for the system to exploit their passion.\n\nThen, there’s the myth that \"anyone can be a writer\". Because, well, from the outside, it seems like you just need to “type words” — and who can’t do that? Especially with the lack of clear barriers to entry in the industry, the temptation to try your luck is strong. And that’s how you get a flood of hopeful aspirants chasing the dream.\n\nThere’s also a social appeal in the image of screenwriters: they are considered above-the-line workers — well-educated, with high earning potential and the possibility of achieving recognition and prestige.\n\nBut there’s something deeper, too. Screenwriting promises something many creative people crave: a unique, non-routine, and potentially rewarding life. For them, instability and precarious working conditions are a price they're willing to pay for the chance to express themselves."
  }
};
